[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.build]
cmds = [
  "cd client-react && npm install && npm run build",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn server.main:app --host 0.0.0.0 --port ${PORT:-8001}"
